// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _2entregaProjetoFinal.Models;

#nullable disable

namespace _2entregaProjetoFinal.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220110200218_Quarto")]
    partial class Quarto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("_2entregaProjetoFinal.Models.Avaliacao", b =>
                {
                    b.Property<int>("IdAvaliacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAvaliacao"), 1L, 1);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdEstabelecimento")
                        .HasColumnType("int");

                    b.HasKey("IdAvaliacao");

                    b.HasIndex("IdEstabelecimento");

                    b.ToTable("avaliacoes");
                });

            modelBuilder.Entity("_2entregaProjetoFinal.Models.CadastrarEstabelecimento", b =>
                {
                    b.Property<int>("IdEstabelecimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstabelecimento"), 1L, 1);

                    b.Property<string>("AcessibilidadesEstabelecimentos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComentariosEstabelecimento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HorarioFuncionamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeEstabelecimento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NotaEstabelecimento")
                        .HasColumnType("int");

                    b.HasKey("IdEstabelecimento");

                    b.ToTable("estabelecimentos");
                });

            modelBuilder.Entity("_2entregaProjetoFinal.Models.CadastrarUsuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"), 1L, 1);

                    b.Property<DateTime>("Data_Nascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("NessecidadeEspecial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("_2entregaProjetoFinal.Models.Avaliacao", b =>
                {
                    b.HasOne("_2entregaProjetoFinal.Models.CadastrarEstabelecimento", "CadastrarEstabelecimento")
                        .WithMany("Avaliacao")
                        .HasForeignKey("IdEstabelecimento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CadastrarEstabelecimento");
                });

            modelBuilder.Entity("_2entregaProjetoFinal.Models.CadastrarEstabelecimento", b =>
                {
                    b.Navigation("Avaliacao");
                });
#pragma warning restore 612, 618
        }
    }
}
